name: accelerator
description: Progetto per ottenere dati dall'accelerometro del dispositivo e plottarli.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.0.1+1


environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  sensors_plus: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true

